Repository MahinRahman8901/c10-Court-Transcript, pull requests merged in 2024-05, with the labels that each got.

#195 Check judges db
  judges/pipeline.py
Labels: enhancement

#200 Fixed eventbridge bug
  terraform/judges_eventbridge.tf
Labels: bug

#208 Add wireframe to readme
  README.md
Labels: documentation

#212 Display case dashboard
  dashboard/case_profiles.py
  dashboard/streamlit_app.py
Labels: enhancement

#216 added catching of error when database does not connect
  dashboard/case_profiles.py
  dashboard/streamlit_app.py
Labels: bug, enhancement

#214 fixed controls
  dashboard/streamlit_app.py
Labels: enhancement

#218 add variables for terraforming
  terraform/main.tf
  terraform/variables.tf
Labels: enhancement

#230 Case count line graph
  dashboard/charts.py
  dashboard/streamlit_app.py
Labels: enhancement

#231 Readded return to get_case_count_line_chart
  dashboard/charts.py
Labels: bug

#237 Reorganise dashboard
  dashboard/case_profiles.py
  dashboard/charts.py
  dashboard/layout.py
  dashboard/streamlit_app.py
Labels: enhancement

#239 Dockerfile copies over new files
  dashboard/Dockerfile
Labels: bug

#240 add terraformed load balancing for products
  terraform/api.tf
  terraform/dashboard.tf
  terraform/main.tf
  terraform/variables.tf
Labels: enhancement

#257 updated dockerfile to catch new directory
  dashboard/Dockerfile
Labels: bug, enhancement
