Repository MahinRahman8901/c10-Court-Transcript, pull requests merged in 2024-04, with the labels that each got.

#62 dockerised and lambdarised etl
  pipeline/Dockerfile
  pipeline/pipeline.py
Labels: enhancement

#74 add terraform script for etl and update etl
  pipeline/load.py
  pipeline/transform.py
  terraform/pipeline/main.tf
  terraform/pipeline/pipeline.tf
  terraform/pipeline/variables.tf
Labels: bug, enhancement

#77 moved terraform files into one folder
  terraform/main.tf
  terraform/pipeline.tf
  terraform/variables.tf
Labels: bug, enhancement

#85 Title cache
  pipeline/extract.py
  pipeline/requirements.txt
Labels: enhancement

#86 updated terraform with eventbridge and updated load script
  pipeline/load.py
  terraform/eventbridge.tf
  terraform/main.tf
  terraform/pipeline.tf
Labels: enhancement

#94 update transform, load and schema
  database/schema.sql
  database/seeds.sql
  pipeline/load.py
  pipeline/transform.py
Labels: bug, enhancement

#101 Extract bug
  pipeline/extract.py
Labels: bug

#109 Beautiful soup tests
  pipeline/test_extract.py
  pipeline/transform.py
Labels: enhancement

#113 update load to get like judge names
  pipeline/load.py
Labels: enhancement

#115 improved schema for unknowns
  database/seeds.sql
Labels: enhancement

#120 Test judge pipeline
  judges/requirements.txt
  judges/test_pipeline.py
Labels: enhancement

#140 Api
  api/app.py
  api/queries.py
  api/requirements.txt
  api/templates/homepage.html
Labels: enhancement

#141 Test judge pipeline
  judges/test_pipeline.py
Labels: enhancement

#147 Dashboard skeleton
  dashboard/dashboard.py
  dashboard/requirements.txt
Labels: enhancement, good first issue

#150 Extract case no
  pipeline/extract.py
Labels: bug

#153 Reverted most of the changes made
  pipeline/extract.py
Labels: enhancement

#170 terraformed api and updated schema
  api/main.tf
  api/variables.tf
  database/schema.sql
  terraform/main.tf
Labels: bug, enhancement

#156 configured schema and updated ETL for formatting date
  pipeline/extract.py
  pipeline/load.py
  pipeline/pipeline.py
  pipeline/transform.py
Labels: bug, enhancement

#172 combined terraform files into one
  terraform/api.tf
  terraform/main.tf
Labels: enhancement

#177 Local v cloud
  pipeline/extract.py
  pipeline/pipeline.py
  pipeline/transform.py
Labels: bug, enhancement

#183 added terraform scripts for dashboard and cleaned api folder
  api/main.tf
  api/variables.tf
  dashboard/Dockerfile
  terraform/api.tf
  terraform/dashboard.tf
Labels: enhancement

#185 Name regex
  pipeline/extract.py
  pipeline/transform.py
Labels: bug, enhancement
